name: nf1-rnaseq
channels:
  - conda-forge
  - bioconda # Don't let bioconda be above conda-forge
  - defaults

dependencies:
  # Core bioinformatics tools
  - sra-tools=3.1.1
  - fastqc=0.12.1
  - trimmomatic=0.39
  - star=2.7.11a
  - subread=2.0.6
  - samtools=1.20 # Very important pin - avoids old zlib issues

  # R base
  - r-base=4.4

  # R packages (CRAN-ish, via conda-forge)
  - r-tidyverse
  - r-pheatmap
  - r-languageserver
  - r-msigdbr

  # R Bioconductor packages
  - bioconductor-deseq2
  - bioconductor-clusterprofiler
  - bioconductor-org.hs.eg.db
  - bioconductor-enhancedvolcano
  - bioconductor-enrichplot
  - bioconductor-apeglm
  - bioconductor-pathview